//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tripasEntities : DbContext
    {
        public tripasEntities()
            : base("name=tripasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amistad> Amistad { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
